plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id("kotlin-kapt")
    id("com.google.dagger.hilt.android")
}

configurations.configureEach {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-stdlib:2.1.21"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.21"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.21"
        eachDependency {
            if (requested.group == "org.jetbrains.kotlin") {
                useVersion("2.1.21")
            }
        }
    }
}

android {
    namespace 'ru.netology.myapp'
    compileSdk 36

    defaultConfig {
        applicationId "ru.netology.myapp"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            manifestPlaceholders["usesCleartextTraffic"] = false
            buildConfigField "String", "BASE_URL", "\"https://10.0.2.2:9999/\""
        }
        debug {
            buildConfigField "String", "BASE_URL", "\"http://10.0.2.2:9999/\""
            manifestPlaceholders["usesCleartextTraffic"] = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    packaging {
        resources {
            excludes += [
                    "META-INF/INDEX.LIST",
                    "META-INF/io.netty.versions.properties",
                    "META-INF/DEPENDENCIES",
                    "META-INF/LICENSE",
                    "META-INF/LICENSE.txt",
                    "META-INF/NOTICE",
                    "META-INF/NOTICE.txt"
            ]
        }
    }

    kapt {
        correctErrorTypes = true
        useBuildCache = false
        includeCompileClasspath = false
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.recyclerview
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx

    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.okhttp
    implementation libs.logging.interceptor
    implementation libs.kotlinx.coroutines.android
    implementation libs.gson
    implementation libs.glide

    implementation "com.google.dagger:hilt-android:2.57.1"
    kapt "com.google.dagger:hilt-android-compiler:2.57.1"

    implementation "com.google.android.gms:play-services-base:18.5.0"

    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    implementation "androidx.paging:paging-runtime-ktx:3.3.6"

    implementation "androidx.room:room-runtime:2.8.4"
    kapt "androidx.room:room-compiler:2.8.4"
    implementation "androidx.room:room-ktx:2.8.4"
}